
(*
    In this file you will implement a function for
    evaluating a parse tree generated by the parser
    functions in "parser.sml".

    Your function should take a parse tree as an
    input and return a real-valued number.
*)

use "parser.sml";

(*
datatype expression =
	Dummy
  | Subtraction of expression * expression
  | Addition of expression * expression
  | Number of real
 *)
  
fun evaluate e =
    case e of
		Addition (e1, e2) 		=> evaluate(e1) + evaluate(e2)
	  | Subtraction (e1, e2)	=> evaluate(e1) - evaluate(e2)
	  | Number e1				=> e1
        

val (lst1, xpr1) = parse exp1
val eval_list1 = evaluate xpr1

val (lst2, xpr2) = parse exp2
val eval_list2 = evaluate xpr2

val (lst3, xpr3) = parse exp3
val eval_list3 = evaluate xpr3